title: Sometimes the reason for something being what it is is deeply hidden from view
author: Somebody who will remain faceless
email: rt@cede.earth
description: > # this means to ignore newlines until "baseurl:"
  A rather pointless display of basic understanding forged from an exercise in playful funfilled delightful joy oozing from a pustulous greedy need to dominate a single page with forethought and common shared meritocritous values of carefully considered words.

theme: minima
# social links
twitter_username: twitterisntforme # DO NOT include the @ character, or else the build will fail!
github_username:  githubisniceisntit # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
